# Generated by Django 4.0 on 2024-04-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingame_name', models.CharField(max_length=255)),
                ('joined_date', models.DateField(null=True)),
            ],
        ),
    ]
