# Generated by Django 5.0.4 on 2024-05-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='game_draw',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='game_lose',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='game_win',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(auto_created=0, null=True),
        ),
    ]
