
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Frame
from PIL import ImageTk
from PIL import Image
import views.gui_gamemode 
import time

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"..\assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

class Loading:
    def __init__(self,root):
        self.root = root

        self.frame = Frame(self.root, bg="#1B2837", width=1300, height=700, 
                           bd=0, relief='ridge', highlightthickness=0)
        self.frame.place(x=0, y=0)

        self.canvas = Canvas(self.frame, bg="#1B2837", width=1300, height=700, 
                             bd=0, relief='ridge', highlightthickness=0)
        self.canvas.place(x=0, y=0)

        self.canvas.create_text(
            578.0,
            144.0,
            anchor="nw",
            text="Đang tải...",
            fill="#FFFFFF",
            font=("Inter Bold", 32 * -1)
        )

        self.angle = 0
        self.image = Image.open(relative_to_assets("loading.png"))
        self.tkimage = ImageTk.PhotoImage(self.image.rotate(self.angle))
        self.canvas_obj = self.canvas.create_image(
            650.0,
            350.0,
            image=self.tkimage
        )

        self.update_image()  # Khởi động vòng lặp cập nhật

        # Cancle btn
        self.button_image_1 = PhotoImage(
            file=relative_to_assets("cancle_findmatches.png"))
        button_1 = Button(
            self.frame,
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command= lambda: self.handle_cancle() ,
            relief="flat"
        )
        button_1.place(
            x=550.0,
            y=521.0,
            width=200.375,
            height=58.0
        )

    def destroy(self):
        self.frame.destroy()

    def handle_cancle(self):
        self.root.controller.show_frame(views.gui_gamemode.GameMode)
    
    def update_image(self):
        self.angle -= 4  # Cập nhật góc xoay
        self.angle %= 360

        self.tkimage = ImageTk.PhotoImage(self.image.rotate(self.angle))
        self.canvas.itemconfig(self.canvas_obj, image=self.tkimage)

        self.frame.after(2, self.update_image)
