
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Frame, messagebox
import views.gui_ranking
import views.gui_gameplay_online, views.gui_gameplay_friend

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"..\assets")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

class GameMode(Frame):
    def __init__(self,parent,controller):
        Frame.__init__(self, parent)

        #region GUI
        canvas = Canvas(
            self,
            bg = "#1B2837",
            height = 700,
            width = 1300,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            133.0,
            101.0,
            1167.0,
            600.0,
            fill="#101B27",
            outline="")

        canvas.create_rectangle(
            610.0,
            153.0,
            1103.0,
            174.0,
            fill="#D9D9D9",
            outline="")

        canvas.create_rectangle(
            1085.7713623046875,
            140.865234375,
            1119.9999961853027,
            184.00011825561523,
            fill="#FF0000",
            outline="")

        canvas.create_text(
            1096.5804443359375,
            149.3232421875,
            anchor="nw",
            text="7",
            fill="#FFFFFF",
            font=("Inter Bold", 24 * -1)
        )

        self.image_image_1 = PhotoImage(
            file=relative_to_assets("logo.png"))
        canvas.create_image(
            368.0,
            303.0,
            image=self.image_image_1
        )

        canvas.create_text(
            170.0,
            438.0,
            anchor="nw",
            text="Caro trực tuyến",
            fill="#FFFFFF",
            font=("DMSans BoldItalic", 50 * -1)
        )

        canvas.create_rectangle(
            610.0,
            153.0,
            972.0,
            174.0,
            fill="#FF00B7",
            outline="")

        canvas.create_text(
            610.0,
            122.0,
            anchor="nw",
            text="Hieudeeptry",
            fill="#FFFFFF",
            font=("Inter Bold", 20 * -1)
        )
        #endregion

        # Play online btn
        self.button_image_1 = PhotoImage(
            file=relative_to_assets("online_play_btn.png"))
        button_1 = Button(
            self,
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: controller.show_frame(views.gui_gameplay_online.GamePlayOnline),
            relief="flat"
        )
        button_1.place(
            x=650.0,
            y=237.0,
            width=396.0,
            height=59.67138671875
        )

        # Play with friend btn
        self.button_image_2 = PhotoImage(
            file=relative_to_assets("play_with_friend_btn.png"))
        button_2 = Button(
            self,
            image=self.button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: controller.show_frame(views.gui_gameplay_friend.GamePlayWithFriend),
            relief="flat"
        )

        button_2.place(
            x=650.0,
            y=320.0,
            width=396.0,
            height=59.67138671875
        )

        # Play with AI btn
        self.button_image_3 = PhotoImage(
            file=relative_to_assets("play_with_ai.png"))
        button_3 = Button(
            self,
            image=self.button_image_3,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: messagebox.showinfo("Play with AI", "Comming soon !"),
            relief="flat"
        )
        button_3.place(
            x=650.0,
            y=403.0,
            width=396.0,
            height=59.67138671875
        )


        # Ranking btn
        self.button_image_4 = PhotoImage(
            file=relative_to_assets("ranking_btn.png"))
        button_4 = Button(
            self,
            image=self.button_image_4,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: controller.show_frame(views.gui_ranking.Ranking),
            relief="flat"
        )
        button_4.place(
            x=694.0,
            y=486.0,
            width=352.0,
            height=54.73684310913086
        )

