
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Frame, messagebox
import views.gui_gamemode

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"..\assets")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

class GamePlay(Frame):
    def __init__(self,parent,controller):
        Frame.__init__(self, parent)

        canvas = Canvas(
            self,
            bg = "#FFFFFF",
            height = 700,
            width = 1300,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            114.0,
            1300.0,
            596.0,
            fill="#101B27",
            outline="")

        canvas.create_rectangle(
            0.0,
            596.0,
            1300.0,
            700.0,
            fill="#1B2837",
            outline="")

        canvas.create_rectangle(
            0.0,
            0.0,
            1300.0,
            114.0,
            fill="#1B2837",
            outline="")

        canvas.create_rectangle(
            179.0,
            54.0,
            194.0,
            69.0,
            fill="#FF0000",
            outline="")

        self.image_image_1 = PhotoImage(
            file=relative_to_assets("avatar_player1.png"))
        canvas.create_image(
            571.0,
            59.0,
            image=self.image_image_1
        )

        self.image_image_2 = PhotoImage(
            file=relative_to_assets("avatar_player2.png"))
        canvas.create_image(
            727.0,
            59.0,
            image=self.image_image_2
        )

        canvas.create_text(
            625.0,
            51.0,
            anchor="nw",
            text="0",
            fill="#FFFFFF",
            font=("Inter SemiBold", 20 * -1)
        )

        canvas.create_text(
            661.0,
            51.0,
            anchor="nw",
            text="0",
            fill="#FFFFFF",
            font=("Inter SemiBold", 20 * -1)
        )

        canvas.create_text(
            477.0,
            70.0,
            anchor="nw",
            text="5:00",
            fill="#FF00D6",
            font=("Inter SemiBold", 16 * -1)
        )

        canvas.create_text(
            778.0,
            70.0,
            anchor="nw",
            text="5:00",
            fill="#FFE500",
            font=("Inter SemiBold", 16 * -1)
        )

        canvas.create_text(
            440.0,
            42.0,
            anchor="nw",
            text="Player 1",
            fill="#FFFFFF",
            font=("Inter Bold", 20 * -1)
        )

        canvas.create_text(
            777.0,
            42.0,
            anchor="nw",
            text="Player 2",
            fill="#FFFFFF",
            font=("Inter Bold", 20 * -1)
        )

        canvas.create_rectangle(
            1104.0,
            53.0,
            1119.0,
            68.0,
            fill="#00FF00",
            outline="")

        canvas.create_rectangle(
            1154.0,
            37.0,
            1183.0,
            85.0,
            fill="#FF0000",
            outline="")

        canvas.create_text(
            1161.0,
            47.0,
            anchor="nw",
            text="7",
            fill="#FFFFFF",
            font=("Inter Bold", 24 * -1)
        )

        canvas.create_rectangle(
            118.0,
            34.0,
            147.0,
            82.0,
            fill="#FF0000",
            outline="")

        canvas.create_text(
            125.0,
            44.0,
            anchor="nw",
            text="7",
            fill="#FFFFFF",
            font=("Inter Bold", 24 * -1)
        )

        # Cancle match
        self.button_image_1 = PhotoImage(
            file=relative_to_assets("cancle_match_btn.png"))
        button_1 = Button(
            self,
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: handle_cancle_match(),
            relief="flat"
        )
        button_1.place(
            x=35.0,
            y=618.0,
            width=200.375,
            height=58.0
        )

        # Input chat
        self.entry_image_1 = PhotoImage(
            file=relative_to_assets("input_chat.png"))
        canvas.create_image(
            890.5,
            648.0,
            image=self.entry_image_1
        )
        entry_1 = Text(
            self,
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0
        )
        entry_1.place(
            x=585.0,
            y=630.0,
            width=611.0,
            height=34.0
        )

        # Icon btn
        self.button_image_2 = PhotoImage(
            file=relative_to_assets("icon_btn.png"))
        button_2 = Button(
            self,
            image=self.button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_2 clicked"),
            relief="flat"
        )
        button_2.place(
            x=1209.0,
            y=630.0,
            width=42.0,
            height=36.0
        )

        canvas.create_rectangle(
            380.0,
            115.0,
            920.0,
            595.0,
            fill="#000000",
            outline="")
        
        def handle_cancle_match():
            result = messagebox.askquestion("Hủy trận đấu","Bạn sẽ được tính là thua cuộc nếu bạn hủy trận đấu")

            if result == 'yes':
                controller.show_frame(views.gui_gamemode.GameMode)