
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"..\assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

window = Tk()

window.geometry("529x293")
window.configure(bg = "#101B27")


canvas = Canvas(
    window,
    bg = "#101B27",
    height = 293,
    width = 529,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    529.0,
    40.0,
    fill="#0C141D",
    outline="")

canvas.create_rectangle(
    0.0,
    253.0,
    529.0,
    293.0,
    fill="#0C141D",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("network_error.png"))
image_1 = canvas.create_image(
    262.0,
    141.0,
    image=image_image_1
)

canvas.create_text(
    181.0,
    64.0,
    anchor="nw",
    text="Đã mất kết nối",
    fill="#FFFFFF",
    font=("DMSans Medium", 26 * -1)
)

canvas.create_text(
    15.0,
    197.0,
    anchor="nw",
    text="Xin vui lòng đợi trong khi chúng tôi kết nối lại với bạn",
    fill="#FFFFFF",
    font=("DMSans Medium", 20 * -1)
)
window.resizable(False, False)
window.mainloop()
