
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Frame
import views.gui_gamemode

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"..\assets")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

class Ranking(Frame):
    def __init__(self,parent,controller):
        Frame.__init__(self, parent)

        canvas = Canvas(
            self,
            bg = "#1B2837",
            height = 700,
            width = 1300,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            1040.0,
            0.0,
            1300.0,
            700.0,
            fill="#101B27",
            outline="")

        canvas.create_rectangle(
            37.0,
            92.0,
            1003.0,
            658.0,
            fill="#213040",
            outline="")

        canvas.create_text(
            120.11376953125,
            35.224853515625,
            anchor="nw",
            text="Bảng xếp hạng",
            fill="#FFFFFF",
            font=("DMSans Medium", 20 * -1)
        )

        canvas.create_text(
            58.0,
            117.0,
            anchor="nw",
            text="Stt",
            fill="#FFFFFF",
            font=("DMSans Bold", 20 * -1)
        )

        canvas.create_text(
            149.666015625,
            117.17333984375,
            anchor="nw",
            text="Tên người chơi",
            fill="#FFFFFF",
            font=("DMSans Bold", 20 * -1)
        )

        canvas.create_text(
            489.427734375,
            117.17333984375,
            anchor="nw",
            text="Thắng/Thua/Hòa",
            fill="#FFFFFF",
            font=("DMSans Bold", 20 * -1)
        )

        canvas.create_text(
            862.0703125,
            117.17333984375,
            anchor="nw",
            text="Điểm",
            fill="#FFFFFF",
            font=("DMSans Bold", 20 * -1)
        )

        # Back btn
        self.button_image_1 = PhotoImage(
            file=relative_to_assets("back_btn.png"))
        button_1 = Button(
            self,
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: controller.show_frame(views.gui_gamemode.GameMode),
            relief="flat"
        )
        button_1.place(
            x=19.0,
            y=19.0,
            width=48.0,
            height=42.0
        )

        image_image_1 = PhotoImage(
            file=relative_to_assets("info_player.png"))
        image_1 = canvas.create_image(
            1170.0,
            132.0,
            image=image_image_1
        )

        canvas.create_rectangle(
            1055.0,
            169.0,
            1285.0,
            243.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            1055.0,
            242.0,
            1285.0,
            316.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            1055.0,
            315.0,
            1285.0,
            389.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            1055.0,
            388.0,
            1285.0,
            462.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            1055.0,
            461.0,
            1285.0,
            535.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            1055.0,
            534.0,
            1285.0,
            608.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            1055.0,
            607.0,
            1285.0,
            681.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            58.0,
            169.0,
            981.63525390625,
            240.98394012451172,
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            58.0,
            240.98388671875,
            981.63525390625,
            313.0,
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            58.0,
            312.9677734375,
            981.63525390625,
            385.0,
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            58.0,
            384.95166015625,
            981.63525390625,
            456.9356002807617,
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            58.0,
            456.935791015625,
            981.63525390625,
            528.9197311401367,
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            58.0,
            528.919677734375,
            981.63525390625,
            600.9036178588867,
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            1123.0,
            27.0,
            1217.0,
            61.0,
            fill="#101B27",
            outline="")

        image_image_2 = PhotoImage(
            file=relative_to_assets("status_online.png"))
        image_2 = canvas.create_image(
            1145.0,
            44.0,
            image=image_image_2
        )

        canvas.create_text(
            1170.0,
            31.0,
            anchor="nw",
            text="1111",
            fill="#FFFFFF",
            font=("DMSans Medium", 20 * -1)
        )
